stages:
  - build

.build:
  image: registry.gitlab.com/rybrow1/unity-docker-builder:2022.3_registered
  stage: build
  tags:
    - desktop-runner
  script:  
    - apt-get install zip git -y  
    - >
      Unity
      -quit
      -batchmode
      -executeMethod BuildProject.${BUILD_TARGET}
      -projectPath ${CI_PROJECT_DIR}
    - zip ${BUILD_TARGET}_build.zip Builds/${BUILD_TARGET}
  artifacts:
    name: ${BUILD_TARGET}
    paths:
      - ${BUILD_TARGET}_build.zip
    expire_in: "1 day"

build: 
  extends: .build
  parallel:
    matrix:
      - BUILD_TARGET:
          - LinuxServer
          - Win64Client
          - Win64Server
  